# Data Science using **Pandas**

##### Useful tips:
- `Shift` + `Tab` for documentation
- `Tab` for autocomplete suggestions

In [1]:
import pandas as pd

In [ ]:
data_number = [1, 2, 3, 4, 5]
data_letter = ['a', 'b', 'c', 'd', 'e']

### `pd` Data Series

In [ ]:
pd.Series(data_number)  # Series is one-dimensional data types can hold any data

In [ ]:
pd.Series(data=data_number, index=data_letter)

In [ ]:
pd.Series(data=data_letter, index=data_number)

In [ ]:
data_dictionary = {'name': 'Johb Marshal', 'age': 44}
pd.Series(data_dictionary)

In [ ]:
num_series = pd.Series(data_number)
let_series = pd.Series(data_letter)
dic_series = pd.Series(data_dictionary)

###### `pd` Series attributes

In [ ]:
num_series.dtype # to check for data type

In [ ]:
num_series.values # to check for data values

In [ ]:
num_series.index # to check for data index

In [ ]:
dic_series.dtype

In [ ]:
dic_series.values

In [ ]:
dic_series.index

In [ ]:
incomplete_data = pd.Series(data=[1, 2, None])

In [ ]:
incomplete_data

In [ ]:
incomplete_data.hasnans # to check if any NaN (Not a Number) data is present

In [ ]:
incomplete_data.size  # number of data contains

In [ ]:
incomplete_data.shape  # columns and lines (rows) of data

###### `pd` Series Methods

In [ ]:
dec_num = pd.Series(data=[0.5, 1.8, 4.5, 2.7, None, 5.5, 0.8, 3.3])

In [ ]:
# Minimum value
dec_num.min()

In [ ]:
# Minimum value index
dec_num.idxmin()

In [ ]:
# Check for the whole data for missing value(s) and return True if a value is NaN, otherwise False
dec_num.isnull()

In [ ]:
# Addition of all values
dec_num.sum()

In [ ]:
# Returns the avarage of all the numbers
dec_num.mean()

### `pd` CSV file

In [13]:
# Loads the csv file as a dataframe (use type() to check), not as a series
# Use pd.read_csv().squeeze() to make it a series for only one column as series is an one-dimensional dataframe
csv_file = pd.read_csv('TopRichestInWorld.csv', usecols=['Name']).squeeze()
csv_file

0                     Elon Musk
1                    Jeff Bezos
2      Bernard Arnault & family
3                    Bill Gates
4                Warren Buffett
                 ...
96             Vladimir Potanin
97         Harold Hamm & family
98                 Sun Piaoyang
99           Luo Liguo & family
100                   Peter Woo
Name: Name, Length: 101, dtype: object

In [11]:
type(csv_file)

pandas.core.series.Series

In [14]:
# To export as csv file (use index=False argument to not save an extra column for index)
csv_file.to_csv('TopRichestInWorld-Names.csv', index=False)

###### Data Preview

In [15]:
csv_data = pd.read_csv('TopRichestInWorld.csv')

In [21]:
# Previewing the dataset of first part
csv_data.head() # first 5 rows without argument
csv_data.head(10) # first 10 rows
csv_data.head(-20) # excluding last 20 rows

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...
76,Stefan Quandt,"$20,700,000,000",55,Germany,BMW,Automotive
77,Jensen Huang,"$20,600,000,000",59,United States,semiconductors,Technology
78,Huang Shilin,"$20,300,000,000",55,China,batteries,Automotive
79,Thomas Peterffy,"$20,100,000,000",77,United States,discount brokerage,Finance & Investments
80,Radhakishan Damani,"$20,000,000,000",67,India,"retail, investments",Fashion & Retail

In [25]:
# Previewing the dataset of last part
csv_data.tail() # last 5 rows without argument
csv_data.tail(10) # last 10 rows
csv_data.tail(-20) # excluding first 20 rows

,Name,NetWorth,Age,Country/Territory,Source,Industry
20,Charles Koch,"$60,000,000,000",86,United States,Koch Industries,Diversified
21,Julia Koch & family,"$60,000,000,000",59,United States,Koch Industries,Diversified
22,Amancio Ortega,"$59,600,000,000",86,Spain,Zara,Fashion & Retail
23,Michael Dell,"$55,100,000,000",57,United States,Dell computers,Technology
24,Zhang Yiming,"$50,000,000,000",38,China,TikTok,Media & Entertainment
...,...,...,...,...,...,...
96,Vladimir Potanin,"$17,300,000,000",61,Russia,metals,Metals & Mining
97,Harold Hamm & family,"$17,200,000,000",76,United States,oil & gas,Energy
98,Sun Piaoyang,"$17,100,000,000",63,China,pharmaceuticals,Healthcare
99,Luo Liguo & family,"$17,000,000,000",66,China,chemicals,Manufacturing
100,Peter Woo,"$17,000,000,000",75,Hong Kong,real estate,Real Estate

###### Data Sorting

In [26]:
csv_data

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...
96,Vladimir Potanin,"$17,300,000,000",61,Russia,metals,Metals & Mining
97,Harold Hamm & family,"$17,200,000,000",76,United States,oil & gas,Energy
98,Sun Piaoyang,"$17,100,000,000",63,China,pharmaceuticals,Healthcare
99,Luo Liguo & family,"$17,000,000,000",66,China,chemicals,Manufacturing
100,Peter Woo,"$17,000,000,000",75,Hong Kong,real estate,Real Estate

In [27]:
csv_data.sort_values('Name', ascending=True)

,Name,NetWorth,Age,Country/Territory,Source,Industry
74,Abigail Johnson,"$21,200,000,000",60,United States,money management,Finance & Investments
42,Alain Wertheimer,"$31,200,000,000",73,France,Chanel,Fashion & Retail
17,Alice Walton,"$65,300,000,000",72,United States,Walmart,Fashion & Retail
22,Amancio Ortega,"$59,600,000,000",86,Spain,Zara,Fashion & Retail
89,Andrew Forrest,"$17,800,000,000",60,Australia,mining,Metals & Mining
...,...,...,...,...,...,...
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
54,William Lei Ding,"$25,200,000,000",50,China,online games,Technology
85,Yang Huiyan & family,"$18,700,000,000",40,China,real estate,Real Estate
24,Zhang Yiming,"$50,000,000,000",38,China,TikTok,Media & Entertainment
16,Zhong Shanshan,"$65,700,000,000",67,China,"beverages, pharmaceuticals",Food & Beverage

In [28]:
csv_data.sort_index(ascending=False)

,Name,NetWorth,Age,Country/Territory,Source,Industry
100,Peter Woo,"$17,000,000,000",75,Hong Kong,real estate,Real Estate
99,Luo Liguo & family,"$17,000,000,000",66,China,chemicals,Manufacturing
98,Sun Piaoyang,"$17,100,000,000",63,China,pharmaceuticals,Healthcare
97,Harold Hamm & family,"$17,200,000,000",76,United States,oil & gas,Energy
96,Vladimir Potanin,"$17,300,000,000",61,Russia,metals,Metals & Mining
...,...,...,...,...,...,...
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive